server:
  port: 8082

spring:
  application:
    name: response-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/resq_response}
      auto-index-creation: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname:${spring.application.name}}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
